name: Update WakaTime stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    environment: wakatime-stats  # Reference the new environment here
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Ensures the correct Node.js version is used
        with:
          node-version: '20'  # Use Node.js 20 explicitly

      - name: Update WakaTime Stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # ['entryPoint', 'args', 'GH_TOKEN', 'WAKATIME_API_KEY', 'SECTION_NAME', 'PULL_BRANCH_NAME', 'PUSH_BRANCH_NAME', 'SHOW_OS', 'SHOW_PROJECTS', 'SHOW_EDITORS', 'SHOW_TIMEZONE', 'SHOW_COMMIT', 'SHOW_LANGUAGE', 'SHOW_LINES_OF_CODE', 'SHOW_LANGUAGE_PER_REPO', 'SHOW_LOC_CHART', 'SHOW_DAYS_OF_WEEK', 'SHOW_PROFILE_VIEWS', 'SHOW_SHORT_INFO', 'SHOW_UPDATED_DATE', 'SHOW_TOTAL_CODE_TIME', 'COMMIT_BY_ME', 'COMMIT_MESSAGE', 'COMMIT_USERNAME', 'COMMIT_EMAIL', 'COMMIT_SINGLE', 'LOCALE', 'UPDATED_DATE_FORMAT', 'IGNORED_REPOS', 'SYMBOL_VERSION', 'DEBUG_LOGGING']
          SHOW_EDITORS: false
          SHOW_OS: false
